spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/join?useSSL=false
    username: dy
    password: 123456
  mail:
    host: smtp.qq.com
    username: 2027972267@qq.com
    password: iffivcgunbgkbicc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  redis:
    database: 0
    host: 127.0.0.1

feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 3000
  ConnetTimeout: 3000
hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.dy.pojo.vo
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  endpoint:
    health:
      show-details: ALWAYS
springcloud-es:
 elasticsearch:
  hostlist: ${eshostlist:127.0.0.1:9200} #多个结点中间用逗号分隔
es:
 index: join
